stages:
  - test
  - deploy


test:
  stage: test
  image: node:latest

  services:
    - mongo

  script:
    - npm install
    - npm run test



  only:
    - master

deploy:
  stage: deploy
  image: kroniak/ssh-client

  before_script:
    - eval $(ssh-agent -s)
    - echo "$MASTER_SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

  script:
    - ssh -o StrictHostKeyChecking=no -i $MASTER_SSH_KEY "${MASTER_SSH_USER}@${MASTER_HOST}" "cd /var/www/mc-server && git pull && npm run build && docker-compose build && docker-compose up"
