language: node_js
node_js:
    - stable
dist: trusty
sudo: false
env:
    - MODE=testing
before_install:
    - openssl aes-256-cbc -K $encrypted_63cbc52e9149_key -iv $encrypted_63cbc52e9149_iv
      -in .travis/deploy_rsa.enc -out .travis/deploy_rsa -d
    - eval "$(ssh-agent -s)"
    - cp .travis/id_rsa ~/.ssh/deploy_rsa
    - chmod 600 ~/.ssh/deploy_rsa
    - ssh-add ~/.ssh/deploy_rsa
install:
    - npm ci
before_script:
    - npm run dev &
script:
    - npm run test
deploy:
    - provider: script
      skip_cleanup: true
      script: ".travis/deploy.sh"
      on:
          branch: master
