language: node_js
node_js:
- stable
dist: trusty
sudo: false
env:
  matrix:
  - MODE=testing
  global:
    secure: B8p1ZlOFb3MNH7cQkLwICkBhMdUPCrae+nuVn8zQpswxwXYF98/C+rWsv8tBQ0IrRMdJazLhaMbu+8Lh19owi38c8qnwEkgXPVidEKcLcDJT6wTRxP7ahoi1Il7A+q8bDrBkSXPXaUWFIh8CgNLf+QyFSvRS5ex6GMN8YtAec0b5tGzyQMC+X6rnpnBD9Nl057eF4R2Hi8ppiYoLLItq8J+vTSgboEAVhtM+0lobW3RD4MgIWqNtCjzFVTpoNbMgOKKS9IW5j5+bqnwaNUIrX5qEbz6I89IKbM95PBI2YFbeFFFk30AeqiQTiyR44P5iII9k/TfDD62c2M0OaxGRMV+SPnUan/ZIgZEu5HWWIfFRDUKWxHl+CcwA0Z8L+nnHNnla1iHkULzTUageoo5SnnOyminQFtavta0+niFMC3OT1yILT/oJ0GFyAgSuLxx3T2xOOFeNranVYl9t+0XKB2ifec2J72hezpkoQ7lvHFIU/gBTV3Jn+tJK/S/YGcHVU487OaXF8rM9x73R9A+kzBZpTOqk4UNB4VfM/ss2GD89pLMrFpFE7t10zwKt3V9FssFUqcLPXMJbnr4VxtKbDH2LWGvpo4CJme2/FvjaKaI0F3kOUo9kqJBuk1uFh65WcoDPKBrqVRLWWlU1v7Y14/ssjq/qf7/8TWifLQppBtQ=
before_install:
- openssl aes-256-cbc -K $encrypted_63cbc52e9149_key -iv $encrypted_63cbc52e9149_iv
  -in .travis/deploy_rsa.enc -out .travis/deploy_rsa -d
- eval "$(ssh-agent -s)"
- cp .travis/id_rsa ~/.ssh/deploy_rsa
- chmod 600 ~/.ssh/deploy_rsa
- ssh-add ~/.ssh/deploy_rsa
install:
- npm ci
before_script:
- npm run dev &
script:
- npm run test
deploy:
- provider: script
  skip_cleanup: true
  script: ".travis/deploy.sh"
  on:
    branch: master
